version: "2"

services:

  api:
    build: .
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - NODE_ENV=dev

  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: yogaccountable
      POSTGRES_PASSWORD: yoga
