version: "2"

services:

  api:
    build: .
    command: npm start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - NODE_ENV=$NODE_ENV

  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_DB: yogaccountable
      POSTGRES_USER: yogaccountable
      POSTGRES_PASSWORD: yoga

  postgres_test:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_DB: yogaccountable_test
      POSTGRES_USER: yogaccountable
      POSTGRES_PASSWORD: yoga
